name: Deploy ML Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Trigger FastAPI Deployment
      run: |
        curl "$FASTAPI_RENDER_HOOK"
      env:
        FASTAPI_RENDER_HOOK: ${{ secrets.FASTAPI_RENDER_HOOK }}

    - name: Trigger Streamlit Deployment
      run: |
        curl "$STREAMLIT_RENDER_HOOK"
      env:
        STREAMLIT_RENDER_HOOK: ${{ secrets.STREAMLIT_RENDER_HOOK }}
